package:
  name: slycot
  version: "0.3.2"

build:
  number: 1
  script:
    - cd {{ environ["RECIPE_DIR"] }}/.. # [not win]
    - cd {{ environ["RECIPE_DIR"] }}\.. # [win]
    - {{ environ["PYTHON"] }} setup.py install

requirements:
  host:
    - python
    - numpy
    - lapack

  build:
    - {{ compiler('fortran') }}
    
  run:
    - python
    - numpy
    - lapack
    - libgfortran

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/Slycot
  license:  GPLv2
  summary: 'A wrapper for the SLICOT control and systems library'
