name: test-env
dependencies:
  # in addtion to package dependencies and explicit LAPACK/BLAS implementations installed in workflow
  - conda-build  # for conda index
  - scipy
  - matplotlib
  - pytest
  - pytest-cov
  - pytest-timeout
  - coverage
  - coveralls
